version: 0.0

os: linux

files:
  - source: python-helloworld.zip
    destination: /tmp

hooks:
  ApplicationStop:
    - run: |
        echo "Stopping python app..."
        # Add your stop command below, e.g.:
        pkill -f "python3 app.py" || echo "App not running"
      runas: ec2-user
      
  AfterInstall:
    - run: |
        cd /tmp
        unzip -o python-helloworld.zip -d /tmp/python-helloworld
      runas: ec2-user

  ApplicationStart:
    - location: /tmp/run.sh
      runas: ec2-user

